#!/usr/bin/env bash
# This is a script that installs HAProxy load balancer
apt-get -y install --no-install-recommends software-properties-common
apt-get -y update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo -e '\nfrontend haproxy\n\tbind :80\n\tdefault_backend servers' >> /etc/haproxy/haproxy.cfg
echo -e '\nbackend servers\n\tserver server1 34.232.52.43\n\tserver server2 54.175.12.49' >> /etc/haproxy/haproxy.cfg
service haproxy restart
