#!/usr/bin/env bash
# This script runs nginx as nginx user
chmod 777 /etc/nginx/nginx.conf
sed -i "s/80 default_server/8080 default_server/" /etc/nginx/sites-available/default
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
pkill -9 apache2
sudo -u nginx service nginx restart
